### ISSUE TITLE
Crash after ~20 seconds

### ISSUE THREAD

**Issue by thesbros** [keijiro/FFmpegOut#1] opened 2017-03-24 03:05 UTC
Unity crashes after recording for more than ~20 seconds.

How to reproduce:

* Open `Test` scene.
* Set `Record Length` on camera to 60.
* Unity crashes after around 20 seconds.

Unity version: 5.5.2f1

**Comment by keijiro** [comment] 2017-03-24 06:53
I paused this project for a while due to other tasks. I'll look into it when resuming the project. Thanks for reporting.

**Comment by daseyb** [comment] 2017-03-24 09:30
This is happening to me too. So far it seems like the ffmpeg process
doesn't close properly.
If you wait for it in a different thread Unity doesn't crash, but the
thread never exits.

**Comment by kornellvarga** [comment] 2017-03-31 08:48
I can confirm as well

**Comment by keijiro** [comment] 2017-04-02 07:50
Hi all,

I guess that it crashed because ffmpeg.exe is missing. I removed it intentionally because it's too big (over 40MB) to add to the repository.

I'll add instruction about it to README later. Please reopen this issue even if it reproduces after adding ffmpeg.exe.

**Comment by daseyb** [comment] 2017-04-02 07:56
I am experiencing the issue with ffmpeg.exe being present. It actually starts the process (it's visible in the windows task manager) and exports short videos fine.

**Comment by thesbros** [comment] 2017-04-02 08:13
I can't reopen - but it definitely still happens with ffmpeg

**Comment by keijiro** [comment] 2017-04-02 08:16
Hmm, okay. Reopened.

I'm refactoring the whole code now. Please verify it after the overhaul.

**Comment by keijiro** [comment] 2017-04-02 13:16
I've refactored the entire code and added an installation note to README.

Please download the following executable and copy it into `Assets/StreamingAssets/FFmpegOut/`.

https://github.com/KeatsPeeks/ffmpeg-static/blob/master/bin/win32/x64/ffmpeg.exe

I think it's almost the same as you used, but I'd like to make sure that it's not an issue depending on the version of ffmpeg.

**Comment by kornellvarga** [comment] 2017-04-02 19:48
Thank you Keijiro for your fast response&fix, I will test it soon

**Comment by kornellvarga** [comment] 2017-04-03 08:13
Seems like more stable, however I am getting some funny results. Big percentage of the .mov s im producing are presenting a picture that is constantly offsetting on the x or y axis (I think depending on the sizing of the window). I am using the ffmpeg.exe you provided a link for. If you want I can share the .mov here

**Comment by keijiro** [comment] 2017-04-03 08:29
Thank you very much for the quick feedback. That's a big progress because I have a clue about that problem (funny constant offsetting). Could you provide information about your graphics card?

**Comment by kornellvarga** [comment] 2017-04-03 08:31
(updated my comment witht the error message that I missed at posting).
I have two 755Ms in a Lenovo Y510P, I have a desktop with an R9 serie if you want I can run a quick test on that too.

**Comment by keijiro** [comment] 2017-04-03 15:21
Thanks for the info. I guess that it's caused by a non-regular screen resolution. I added "Set Resolution" property to avoid this problem. Could you give a try at it?

**Comment by kornellvarga** [comment] 2017-04-04 10:23
yes, it did solve the running picture issue! however now during recording the there is no camera on the Display 1, is that intentional?

**Comment by keijiro** [comment] 2017-04-04 10:51
Yes. It grabs the output of the camera, so that the game view goes blank. It's a little bit difficult to resend the output to the same game view. I added a preview area to the inspector as a workaround.

Personally, I'm okay with this design because mainly I'm using this for non-interactive projects. What do you think about it? Any suggestion is welcomed.

**Comment by keijiro** [comment] 2017-04-04 13:53
By the way, I added a workaround for the problem. Now the game view keeps displaying during recording.

**Comment by kornellvarga** [comment] 2017-04-04 14:41
I have yet to test it with VR. I would render an additional camera that does not render to the eyes (openvr), so I guess recording that will have to work perfectly. I will get back to you with my findings.

**Comment by daseyb** [comment] 2017-04-04 20:12
I'm on vacation right now, but I'll also make sure to test it once I'm back home.

Thanks for the work and the quick fixes!

**Comment by keijiro** [comment] 2017-04-09 08:04
I'm closing this issue. Please feel free to reopen (or poke with @keijiro ) when reproducing this with the latest version.

**Closed by keijiro** 2017-04-09 08:04 UTC
Labels: bug
